# Generated by Django 4.2.7 on 2023-11-20 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0002_alter_userinfo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'В процессе'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('address_option', models.CharField(choices=[('default', 'Использовать адрес по умолчанию'), ('new', 'Введите новый адрес')], default='default', max_length=150)),
                ('order_products', models.ManyToManyField(to='store_app.product')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
