# Generated by Django 4.2.7 on 2023-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
